version: "3.8"

services:
  async_challenge:
    container_name: async_challenge
    hostname: async_challenge
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
      - '8085:8085'
    env_file:
      - docker/.env
    depends_on:
      - redis
      #- postgres
  # postgres:
  #   container_name: postgres
  #   hostname: postgres
  #   image: postgres:12-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: itsasecret
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - 'pgdata:/var/lib/postgresql/data'
  #     - './docker/database:/docker-entrypoint-initdb.d'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis-persistence:/bitnami/redis/data
    # depends_on:
    #   - postgres
volumes:
  pgdata:
  jsdata:
